[build]
  command = "npm install && ng build --configuration=production"
  publish = "dist/nsm/browser" # change this to your actual dist folder name

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
